server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: ai-invest
  datasource:
    url: jdbc:mysql://localhost:3306/ai-invest
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #等待连接池分配连接的最长时间，单位是毫秒
      connection-timeout: 20000
      #连接池中保持的最小空闲连接数
      minimum-idle: 5
      #连接池中最大连接数
      maximum-pool-size: 20
      #连接在池中空闲的最大时间，超过这个时间将被关闭，单位是毫秒
      idle-timeout: 300000
      #连接的最大生命周期，超过这个时间将被关闭，单位是毫秒
      max-lifetime: 2000000
# swak 文档配置
knife4j:
  enable: true
  cors: true
  openapi:
    title: "ai-invest"
    concat: "ljq"
    version: "1.0.0"
    group:
      admin:
        groupName: "C端业务"
        api-rule-resources:
          - "com.swak.ai.invest.web.api.controller"
    url: "http://localhost:8081/doc.html"

swak:
  log-trace:
    headers:
      - token
      - marketCode
  http-client:
    connect-timeout: 3000
    socket-timeout: 6000
    config:
      xueqiu:
        url: "https://stock.xueqiu.com"
        connect-timeout: 3000
        socket-timeout: 60000
        connection-request-timeout: 3000
      api2:
        url: http://example.com/api2
        default-max-per-route: 30
        max-total: 150
        connection-request-timeout: 1500
        connect-timeout: 1500
        socket-timeout: 15000

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine #other choose：caffeine
      keyConvertor: fastjson2 #other choose：fastjson/jackson
      limit: 10000

